# 模組載入器
modLoader="javafml"
# Forge API 版本
loaderVersion="[47,)"
# 授權條款
license="BSD 3-Clause"
# 顯示在模組列表的連結
[[mods]]
modId="bdstw_teamsystem"
version="${file.jarVersion}"
displayName="BDSTW 隊伍系統"
logoFile="logo.png"
authors="BDSTW"
description='''
一個功能強大的隊伍系統，包含隊伍隨機傳送 (RTP) 功能。
'''
# Forge 和 Minecraft 的依賴關係
[[dependencies.bdstw_teamsystem]]
modId="forge"
mandatory=true
versionRange="[47.3.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.bdstw_teamsystem]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
